[package]
name = "zip_partitioner"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "0.6"
rfd = "0.14"
anyhow = "1"
thiserror = "1"
indicatif = "0.17"
rayon = "1.8"

[build-dependencies]
winres = "0.1"